### PR TITLE
Add website with framework

### PR DESCRIPTION
**Pull request by fabricio-garcia**
Added the HTML and styled cloned website.

Cloned website can be found [here](https://app.pluralsight.com/id?redirectTo=%2Fid%2Fdashboard)

### CODE REVIEW

**Comment by fabricio-garcia** [comment]
# Design Your Own Grid-based Framework

## [Collaborative Project]

This assignment consists of building a grid-based framework (similar to bootstrap) that includes some basic functionality necessary to build a website.

You can find the original project specification [here](https://www.theodinproject.com/courses/html5-and-css3/lessons/design-your-own-grid-based-framework).

## Additional Microverse Adjustments

### General

- It includes a descriptive README file.
- Inline comments only when considered necessary.
- Files not related to the project are added to `.gitignore`.
- Code is kept [clean](https://www.w3schools.com/html/html5_syntax.asp).
- [Semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp) is used
- HTML markup is validated with <https://validator.w3.org/#validate_by_upload>.
- [Common mistakes](https://speckyboy.com/good-bad-css-practices/) are avoided in the CSS styles.

### Project specific

- The cloned website can be accesed [here](https://app.pluralsight.com/id?redirectTo=%2Fid%2Fdashboard)
- The cloned site was created with responsiveness in mind.
- There are 3 breakpoints:
  - breakpoint for small screens with a width of up to 720px.
  - breakpoint for medium screens with a width in the range of 720px - 1024px.
  - breakpoint for large screens with width above 1024px

**Comment by fabricio-garcia** [comment]
# Important!

**To the reviewer:**

I sent this project to revision 2 days ago and @whiz25 answer this:

Ashampoo_Snap_lunes, 7 de octubre de 2019_10h49m26s_001_

In the same content that @whiz25 pointed me out there's a video that indicating projects have a development branch. As you may comprehend this is very confusing, specially since in my last project another reviewer indicated me that I should include a development branch.

I already removed the development branch and merged the branches directly in master as indicated.

**Comment by whiz25** [comment]
@fabricio-garcia I am so sorry that there has been confusion because of the reviews you had from previous TSE's. At the start of last week, we were informed as reviewers that any repo that has a development branch for a course before ```Advanced Building Blocks - Enumerables``` in ruby is invalid. Note that this change was effected last week meaning it is new.
So what qualifies a PR to be valid?
- [ ] the repo must, of course, has the master branch
- [ ] and descriptive feature branches. A feature branch could be something like ```user-sign-in-feature```, etc.

So any repo that doesn't follow the above guidelines must be marked invalid and no review must take place. This is why your repo was marked invalid.
Please remove the development branch and resubmit for another review. If you are still not convinced, maybe you can reach out to @emily or @lydia on slack.

**Comment by lydia** [comment]
FYI @whiz25 if you @ a handle in a pull request or github issue, it notifies the person who owns that handle and might notify someone you didn't mean to.

**Pull request merged**
